(TeX-add-style-hook
 "references"
 (lambda ()
   (LaTeX-add-bibitems
    "TechnologyTippingPoints"
    "BlockchainAdoptionsMaritime"
    "EthereumWhitepaper"
    "HereHowMuch"
    "SmartContractsMarket"
    "CryptocurrencyStatistics20232023"
    "nakamotoBitcoinPeertoPeerElectronic"
    "Code4renaKeepingHigh"
    "Sherlock"
    "woodETHEREUMSECUREDECENTRALISED"
    "SoliditySolidity22"
    "zhangDemystifyingExploitableBugs2023a"
    "Solodit_contentReport_tagsMd"
    "timeMostInterestingWeb32023"
    "JudgingCriteria"
    "JCPFreeFullText"
    "scharDecentralizedFinanceBlockchain"
    "meyerDecentralizedFinanceSystematic2022"
    "gramlichMultivocalLiteratureReview2023"
    "chenBlockchainDisruptionDecentralized2020"
    "CompetitiveVsPrivate"
    "DefiLlama"
    "bittencourtSolidityCommonVulnerabilities2023"
    "TuringCompleteness2023"
    "KEVMCompleteFormal"
    "hasinADSBBasedAir2021"
    "ibrahimDDoSAttackPrevention2022"
    "rupaIndustryEthereumBlockchain2021"
    "zhangSoKBlockchainDecentralization2023"))
 '(or :bibtex :latex))

